# All the digital pins for the motors
BOTTOM_MOTOR_STEP_PIN = 2
BOTTOM_MOTOR_DIR_PIN = 8

LEFT_MOTOR_STEP_PIN = 3
LEFT_MOTOR_DIR_PIN = 9

BACK_MOTOR_STEP_PIN = 0
BACK_MOTOR_DIR_PIN = 0

RIGHT_MOTOR_STEP_PIN = 0
RIGHT_MOTOR_DIR_PIN = 0

TOP_MOTOR_STEP_PIN = 0
TOP_MOTOR_DIR_PIN = 0

FRONT_MOTOR_STEP_PIN = 0
FRONT_MOTOR_DIR_PIN = 0