# All the digital pins for the motors
BOTTOM_MOTOR_STEP_PIN = 6
BOTTOM_MOTOR_DIR_PIN = 9

LEFT_MOTOR_STEP_PIN = 0
LEFT_MOTOR_DIR_PIN = 0

BACK_MOTOR_STEP_PIN = 0
BACK_MOTOR_DIR_PIN = 0

RIGHT_MOTOR_STEP_PIN = 0
RIGHT_MOTOR_DIR_PIN = 0

TOP_MOTOR_STEP_PIN = 0
TOP_MOTOR_DIR_PIN = 0

FRONT_MOTOR_STEP_PIN = 0
FRONT_MOTOR_DIR_PIN = 0